
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Item
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum ItemType
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 正常无逻辑
        /// </summary>
        NORMAL = 1,
        /// <summary>
        /// 武器碎片会根据数量动态改变稀有度
        /// </summary>
        WEAPONPIECE = 2,
    }

} 

