
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.chest
{
public sealed partial class ChestLoop : Luban.BeanBase
{
    public ChestLoop(JSONNode _buf) 
    {
        { if(!_buf["score"].IsNumber) { throw new SerializationException(); }  Score = _buf["score"]; }
        { if(!_buf["reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["reward"]; }
        Reward_Ref = null;
    }

    public static ChestLoop DeserializeChestLoop(JSONNode _buf)
    {
        return new chest.ChestLoop(_buf);
    }

    /// <summary>
    /// 积分数
    /// </summary>
    public readonly int Score;
    /// <summary>
    /// 发放的宝箱ID
    /// </summary>
    public readonly int Reward;
    public item.Item Reward_Ref;
   
    public const int __ID__ = 407045752;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Reward_Ref = tables.Item.GetOrDefault(Reward);
    }

    public override string ToString()
    {
        return "{ "
        + "score:" + Score + ","
        + "reward:" + Reward + ","
        + "}";
    }
}

}

