
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbdungeon
{
/// <summary>
/// 关卡玩家升级
/// </summary>
public partial class DungeonExp
{
    private readonly System.Collections.Generic.Dictionary<int, dungeon.DungeonExp> _dataMap;
    private readonly System.Collections.Generic.List<dungeon.DungeonExp> _dataList;
    
    public DungeonExp(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dungeon.DungeonExp>();
        _dataList = new System.Collections.Generic.List<dungeon.DungeonExp>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            dungeon.DungeonExp _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.dungeon.DungeonExp.DeserializeDungeonExp(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, dungeon.DungeonExp> DataMap => _dataMap;
    public System.Collections.Generic.List<dungeon.DungeonExp> DataList => _dataList;

    public dungeon.DungeonExp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public dungeon.DungeonExp Get(int key) => _dataMap[key];
    public dungeon.DungeonExp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

