
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbdungeon
{
/// <summary>
/// 关卡表
/// </summary>
public partial class Dungeon
{
    private readonly System.Collections.Generic.Dictionary<int, dungeon.Dungeon> _dataMap;
    private readonly System.Collections.Generic.List<dungeon.Dungeon> _dataList;
    
    public Dungeon(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dungeon.Dungeon>();
        _dataList = new System.Collections.Generic.List<dungeon.Dungeon>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            dungeon.Dungeon _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.dungeon.Dungeon.DeserializeDungeon(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, dungeon.Dungeon> DataMap => _dataMap;
    public System.Collections.Generic.List<dungeon.Dungeon> DataList => _dataList;

    public dungeon.Dungeon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public dungeon.Dungeon Get(int key) => _dataMap[key];
    public dungeon.Dungeon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

