
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbdungeon
{
public partial class Wave
{
    private readonly System.Collections.Generic.Dictionary<int, dungeon.Wave> _dataMap;
    private readonly System.Collections.Generic.List<dungeon.Wave> _dataList;
    
    public Wave(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dungeon.Wave>();
        _dataList = new System.Collections.Generic.List<dungeon.Wave>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            dungeon.Wave _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.dungeon.Wave.DeserializeWave(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, dungeon.Wave> DataMap => _dataMap;
    public System.Collections.Generic.List<dungeon.Wave> DataList => _dataList;

    public dungeon.Wave GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public dungeon.Wave Get(int key) => _dataMap[key];
    public dungeon.Wave this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

