
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbenemy
{
/// <summary>
/// 敌人等级
/// </summary>
public partial class EnemyLevel
{
    private readonly System.Collections.Generic.Dictionary<int, enemy.EnemyLevel> _dataMap;
    private readonly System.Collections.Generic.List<enemy.EnemyLevel> _dataList;
    
    public EnemyLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, enemy.EnemyLevel>();
        _dataList = new System.Collections.Generic.List<enemy.EnemyLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            enemy.EnemyLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.enemy.EnemyLevel.DeserializeEnemyLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, enemy.EnemyLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<enemy.EnemyLevel> DataList => _dataList;

    public enemy.EnemyLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemy.EnemyLevel Get(int key) => _dataMap[key];
    public enemy.EnemyLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

