
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbenemy
{
/// <summary>
/// 敌人
/// </summary>
public partial class Enemy
{
    private readonly System.Collections.Generic.Dictionary<int, enemy.Enemy> _dataMap;
    private readonly System.Collections.Generic.List<enemy.Enemy> _dataList;
    
    public Enemy(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, enemy.Enemy>();
        _dataList = new System.Collections.Generic.List<enemy.Enemy>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            enemy.Enemy _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.enemy.Enemy.DeserializeEnemy(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, enemy.Enemy> DataMap => _dataMap;
    public System.Collections.Generic.List<enemy.Enemy> DataList => _dataList;

    public enemy.Enemy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemy.Enemy Get(int key) => _dataMap[key];
    public enemy.Enemy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

