
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbenemy
{
/// <summary>
/// 敌人等级
/// </summary>
public partial class EnemyLevel
{
    private readonly System.Collections.Generic.List<enemy.EnemyLevel> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), enemy.EnemyLevel> _dataMapUnion;

    public EnemyLevel(JSONNode _buf)
    {
        _dataList = new System.Collections.Generic.List<enemy.EnemyLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            enemy.EnemyLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.enemy.EnemyLevel.DeserializeEnemyLevel(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), enemy.EnemyLevel>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<enemy.EnemyLevel> DataList => _dataList;

    public enemy.EnemyLevel Get(int id, int level) => _dataMapUnion.TryGetValue((id, level), out enemy.EnemyLevel __v) ? __v : null;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

