
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbenemy
{
/// <summary>
/// 敌人类型表
/// </summary>
public partial class EnemyTypeIndex
{
    private readonly System.Collections.Generic.Dictionary<Enums.Enemy.Type, enemy.EnemyTypeIndex> _dataMap;
    private readonly System.Collections.Generic.List<enemy.EnemyTypeIndex> _dataList;
    
    public EnemyTypeIndex(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<Enums.Enemy.Type, enemy.EnemyTypeIndex>();
        _dataList = new System.Collections.Generic.List<enemy.EnemyTypeIndex>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            enemy.EnemyTypeIndex _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.enemy.EnemyTypeIndex.DeserializeEnemyTypeIndex(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EnemyType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<Enums.Enemy.Type, enemy.EnemyTypeIndex> DataMap => _dataMap;
    public System.Collections.Generic.List<enemy.EnemyTypeIndex> DataList => _dataList;

    public enemy.EnemyTypeIndex GetOrDefault(Enums.Enemy.Type key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemy.EnemyTypeIndex Get(Enums.Enemy.Type key) => _dataMap[key];
    public enemy.EnemyTypeIndex this[Enums.Enemy.Type key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

