
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.shop
{
public sealed partial class drawLevel : Luban.BeanBase
{
    public drawLevel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["next_exp_require"].IsNumber) { throw new SerializationException(); }  NextExpRequire = _buf["next_exp_require"]; }
        { var __json0 = _buf["probs"]; if(!__json0.IsArray) { throw new SerializationException(); } Probs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Probs.Add(__v0); }   }
    }

    public static drawLevel DeserializedrawLevel(JSONNode _buf)
    {
        return new shop.drawLevel(_buf);
    }

    /// <summary>
    /// 当前等级
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升至下一级所需经验<br/>（抽卡数量）
    /// </summary>
    public readonly int NextExpRequire;
    /// <summary>
    /// 抽卡概率分布<br/>（绿蓝紫橙红）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Probs;
   
    public const int __ID__ = -1026516056;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nextExpRequire:" + NextExpRequire + ","
        + "probs:" + Luban.StringUtil.CollectionToString(Probs) + ","
        + "}";
    }
}

}

