
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 卡牌效果
/// </summary>
public sealed partial class card_Effects : Luban.BeanBase
{
    public card_Effects(JSONNode _buf) 
    {
        { if(!_buf["effect_type"].IsNumber) { throw new SerializationException(); }  EffectType = (Enums.Card.EffectsType)_buf["effect_type"].AsInt; }
        { var __json0 = _buf["int_params"]; if(!__json0.IsArray) { throw new SerializationException(); } IntParams = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  IntParams.Add(__v0); }   }
    }

    public static card_Effects Deserializecard_Effects(JSONNode _buf)
    {
        return new Beans.card_Effects(_buf);
    }

    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly Enums.Card.EffectsType EffectType;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> IntParams;
   
    public const int __ID__ = -2120385506;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "effectType:" + EffectType + ","
        + "intParams:" + Luban.StringUtil.CollectionToString(IntParams) + ","
        + "}";
    }
}

}

