
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 值-资源对
/// </summary>
public sealed partial class Com_ValueResPair : Luban.BeanBase
{
    public Com_ValueResPair(JSONNode _buf) 
    {
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
        { if(!_buf["item_require"].IsObject) { throw new SerializationException(); }  ItemRequire = global::cfg.Beans.Item_Require.DeserializeItem_Require(_buf["item_require"]);  }
    }

    public static Com_ValueResPair DeserializeCom_ValueResPair(JSONNode _buf)
    {
        return new Beans.Com_ValueResPair(_buf);
    }

    /// <summary>
    /// 整型类型
    /// </summary>
    public readonly int Value;
    /// <summary>
    /// 要求的道具
    /// </summary>
    public readonly Beans.Item_Require ItemRequire;
   
    public const int __ID__ = -1228317934;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ItemRequire?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "itemRequire:" + ItemRequire + ","
        + "}";
    }
}

}

