
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 解锁条件组
/// </summary>
public sealed partial class Com_UnlockConds : Luban.BeanBase
{
    public Com_UnlockConds(JSONNode _buf) 
    {
        { if(!_buf["cond_type"].IsNumber) { throw new SerializationException(); }  CondType = (Enums.Com.CondType)_buf["cond_type"].AsInt; }
        { var __json0 = _buf["string_params"]; if(!__json0.IsArray) { throw new SerializationException(); } StringParams = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  StringParams.Add(__v0); }   }
        { var __json0 = _buf["int_params"]; if(!__json0.IsArray) { throw new SerializationException(); } IntParams = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  IntParams.Add(__v0); }   }
    }

    public static Com_UnlockConds DeserializeCom_UnlockConds(JSONNode _buf)
    {
        return new Beans.Com_UnlockConds(_buf);
    }

    /// <summary>
    /// 整型类型
    /// </summary>
    public readonly Enums.Com.CondType CondType;
    /// <summary>
    /// 字符串参数
    /// </summary>
    public readonly System.Collections.Generic.List<string> StringParams;
    /// <summary>
    /// 整型参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> IntParams;
   
    public const int __ID__ = -707002012;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "condType:" + CondType + ","
        + "stringParams:" + Luban.StringUtil.CollectionToString(StringParams) + ","
        + "intParams:" + Luban.StringUtil.CollectionToString(IntParams) + ","
        + "}";
    }
}

}

