
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
public sealed partial class Com_ParamType : Luban.BeanBase
{
    public Com_ParamType(JSONNode _buf) 
    {
        { if(!_buf["INT"].IsNumber) { throw new SerializationException(); }  INT = _buf["INT"]; }
    }

    public static Com_ParamType DeserializeCom_ParamType(JSONNode _buf)
    {
        return new Beans.Com_ParamType(_buf);
    }

    /// <summary>
    /// 整型类型
    /// </summary>
    public readonly int INT;
   
    public const int __ID__ = -1093894178;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "INT:" + INT + ","
        + "}";
    }
}

}

