
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 传送门数据
/// </summary>
public sealed partial class Dungeon_Portals : Luban.BeanBase
{
    public Dungeon_Portals(JSONNode _buf) 
    {
        { if(!_buf["position"].IsObject) { throw new SerializationException(); }  Position = ExternalTypeUtil.NewVector2(global::cfg.Vector2.DeserializeVector2(_buf["position"]));  }
        { if(!_buf["wave_id"].IsNumber) { throw new SerializationException(); }  WaveId = _buf["wave_id"]; }
        WaveId_Ref = null;
    }

    public static Dungeon_Portals DeserializeDungeon_Portals(JSONNode _buf)
    {
        return new Beans.Dungeon_Portals(_buf);
    }

    /// <summary>
    /// 传送门坐标
    /// </summary>
    public readonly UnityEngine.Vector2 Position;
    /// <summary>
    /// 传送门绑定的波次id
    /// </summary>
    public readonly int WaveId;
    public dungeon.DungeonWave WaveId_Ref;
   
    public const int __ID__ = -1336252553;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        WaveId_Ref = tables.DungeonWave.GetOrDefault(WaveId);
    }

    public override string ToString()
    {
        return "{ "
        + "position:" + Position + ","
        + "waveId:" + WaveId + ","
        + "}";
    }
}

}

