
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 敌人诞生配置方式
/// </summary>
public sealed partial class Enemy_Init : Luban.BeanBase
{
    public Enemy_Init(JSONNode _buf) 
    {
        { if(!_buf["enemy_id"].IsNumber) { throw new SerializationException(); }  EnemyId = _buf["enemy_id"]; }
        EnemyId_Ref = null;
        { var __json0 = _buf["angles"]; if(!__json0.IsArray) { throw new SerializationException(); } Angles = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Angles.Add(__v0); }   }
    }

    public static Enemy_Init DeserializeEnemy_Init(JSONNode _buf)
    {
        return new Beans.Enemy_Init(_buf);
    }

    /// <summary>
    /// 整型类型
    /// </summary>
    public readonly int EnemyId;
    public enemy.Enemy EnemyId_Ref;
    /// <summary>
    /// 角度（有几个会生成几个）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Angles;
   
    public const int __ID__ = -984560686;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        EnemyId_Ref = tables.Enemy.GetOrDefault(EnemyId);
    }

    public override string ToString()
    {
        return "{ "
        + "enemyId:" + EnemyId + ","
        + "angles:" + Luban.StringUtil.CollectionToString(Angles) + ","
        + "}";
    }
}

}

