
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 投放道具要求（带概率）
/// </summary>
public sealed partial class Item_Draw : Luban.BeanBase
{
    public Item_Draw(JSONNode _buf) 
    {
        { if(!_buf["res_type"].IsNumber) { throw new SerializationException(); }  ResType = (Enums.Com.ResourceType)_buf["res_type"].AsInt; }
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        Id_Ref = null;
        { if(!_buf["number"].IsNumber) { throw new SerializationException(); }  Number = _buf["number"]; }
        { if(!_buf["prop"].IsNumber) { throw new SerializationException(); }  Prop = _buf["prop"]; }
    }

    public static Item_Draw DeserializeItem_Draw(JSONNode _buf)
    {
        return new Beans.Item_Draw(_buf);
    }

    /// <summary>
    /// 资源类型
    /// </summary>
    public readonly Enums.Com.ResourceType ResType;
    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    public item.Item Id_Ref;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 概率/权重
    /// </summary>
    public readonly float Prop;
   
    public const int __ID__ = -1263007387;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Id_Ref = tables.Item.GetOrDefault(Id);
    }

    public override string ToString()
    {
        return "{ "
        + "resType:" + ResType + ","
        + "id:" + Id + ","
        + "number:" + Number + ","
        + "prop:" + Prop + ","
        + "}";
    }
}

}

