
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 投放道具要求（带概率）
/// </summary>
public sealed partial class Item_Draw : Luban.BeanBase
{
    public Item_Draw(JSONNode _buf) 
    {
        { if(!_buf["res_type"].IsNumber) { throw new SerializationException(); }  ResType = (Enums.Com.ResourceType)_buf["res_type"].AsInt; }
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["number"].IsNumber) { throw new SerializationException(); }  Number = _buf["number"]; }
        { var _j = _buf["prop"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  Prop = _j; } } else { Prop = null; } }
    }

    public static Item_Draw DeserializeItem_Draw(JSONNode _buf)
    {
        return new Beans.Item_Draw(_buf);
    }

    /// <summary>
    /// 资源类型
    /// </summary>
    public readonly Enums.Com.ResourceType ResType;
    /// <summary>
    /// 资源id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 概率/权重
    /// </summary>
    public readonly int? Prop;
   
    public const int __ID__ = -1263007387;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "resType:" + ResType + ","
        + "id:" + Id + ","
        + "number:" + Number + ","
        + "prop:" + Prop + ","
        + "}";
    }
}

}

