
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 道具要求
/// </summary>
public sealed partial class Item_Require : Luban.BeanBase
{
    public Item_Require(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        Id_Ref = null;
        { if(!_buf["require"].IsNumber) { throw new SerializationException(); }  Require = _buf["require"]; }
    }

    public static Item_Require DeserializeItem_Require(JSONNode _buf)
    {
        return new Beans.Item_Require(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    public item.Item Id_Ref;
    /// <summary>
    /// 要几个
    /// </summary>
    public readonly int Require;
   
    public const int __ID__ = 1138206116;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Id_Ref = tables.Item.GetOrDefault(Id);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "require:" + Require + ","
        + "}";
    }
}

}

