
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Beans
{
/// <summary>
/// 在关卡波次中生成怪物
/// </summary>
public sealed partial class Wave_EnemyCreate : Luban.BeanBase
{
    public Wave_EnemyCreate(JSONNode _buf) 
    {
        { if(!_buf["init_time"].IsNumber) { throw new SerializationException(); }  InitTime = _buf["init_time"]; }
        { if(!_buf["enemy_init"].IsObject) { throw new SerializationException(); }  EnemyInit = global::cfg.Beans.Enemy_Init.DeserializeEnemy_Init(_buf["enemy_init"]);  }
    }

    public static Wave_EnemyCreate DeserializeWave_EnemyCreate(JSONNode _buf)
    {
        return new Beans.Wave_EnemyCreate(_buf);
    }

    /// <summary>
    /// 生成时间
    /// </summary>
    public readonly float InitTime;
    /// <summary>
    /// 敌人id和数量
    /// </summary>
    public readonly Beans.Enemy_Init EnemyInit;
   
    public const int __ID__ = -1465421239;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        EnemyInit?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "initTime:" + InitTime + ","
        + "enemyInit:" + EnemyInit + ","
        + "}";
    }
}

}

