
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.avg
{
public sealed partial class AvgEvent : Luban.BeanBase
{
    public AvgEvent(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["text_color"].IsNumber) { throw new SerializationException(); }  TextColor = _buf["text_color"]; }
        TextColor_Ref = null;
        { if(!_buf["time_delay"].IsNumber) { throw new SerializationException(); }  TimeDelay = _buf["time_delay"]; }
        { if(!_buf["time_duration"].IsNumber) { throw new SerializationException(); }  TimeDuration = _buf["time_duration"]; }
        { if(!_buf["text_str"].IsString) { throw new SerializationException(); }  TextStr = _buf["text_str"]; }
    }

    public static AvgEvent DeserializeAvgEvent(JSONNode _buf)
    {
        return new avg.AvgEvent(_buf);
    }

    /// <summary>
    /// avg_id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 字体颜色
    /// </summary>
    public readonly int TextColor;
    public com.Color TextColor_Ref;
    /// <summary>
    /// 文本是否需要延后出现时间(s)
    /// </summary>
    public readonly float TimeDelay;
    /// <summary>
    /// 持续时间(s)
    /// </summary>
    public readonly float TimeDuration;
    /// <summary>
    /// 文本
    /// </summary>
    public readonly string TextStr;
   
    public const int __ID__ = -274406748;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        TextColor_Ref = tables.Color.GetOrDefault(TextColor);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "textColor:" + TextColor + ","
        + "timeDelay:" + TimeDelay + ","
        + "timeDuration:" + TimeDuration + ","
        + "textStr:" + TextStr + ","
        + "}";
    }
}

}

