
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.avg
{
public sealed partial class AvgStory : Luban.BeanBase
{
    public AvgStory(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["trigger"].IsObject) { throw new SerializationException(); }  Trigger = global::cfg.Beans.Com_Trigger.DeserializeCom_Trigger(_buf["trigger"]);  }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<Beans.Com_UnlockConds>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Beans.Com_UnlockConds __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Beans.Com_UnlockConds.DeserializeCom_UnlockConds(__e0);  }  UnlockConds.Add(__v0); }   }
        { if(!_buf["id_start"].IsNumber) { throw new SerializationException(); }  IdStart = _buf["id_start"]; }
        IdStart_Ref = null;
        { if(!_buf["id_end"].IsNumber) { throw new SerializationException(); }  IdEnd = _buf["id_end"]; }
        { if(!_buf["can_recur"].IsBoolean) { throw new SerializationException(); }  CanRecur = _buf["can_recur"]; }
    }

    public static AvgStory DeserializeAvgStory(JSONNode _buf)
    {
        return new avg.AvgStory(_buf);
    }

    /// <summary>
    /// avg_id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 触发时点
    /// </summary>
    public readonly Beans.Com_Trigger Trigger;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly System.Collections.Generic.List<Beans.Com_UnlockConds> UnlockConds;
    /// <summary>
    /// avg起始事件id
    /// </summary>
    public readonly int IdStart;
    public avg.AvgEvent IdStart_Ref;
    /// <summary>
    /// avg终止事件id<br/>（如果找不到id会一直+1寻找）
    /// </summary>
    public readonly int IdEnd;
    /// <summary>
    /// 是否允许反复触发
    /// </summary>
    public readonly bool CanRecur;
   
    public const int __ID__ = -261527297;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Trigger?.ResolveRef(tables);
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
        IdStart_Ref = tables.AvgEvent.GetOrDefault(IdStart);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "trigger:" + Trigger + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "idStart:" + IdStart + ","
        + "idEnd:" + IdEnd + ","
        + "canRecur:" + CanRecur + ","
        + "}";
    }
}

}

