
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["text_name"].IsString) { throw new SerializationException(); }  TextName = _buf["text_name"]; }
        { if(!_buf["text_desc"].IsString) { throw new SerializationException(); }  TextDesc = _buf["text_desc"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (Enums.Com.Quality)_buf["quality"].AsInt; }
        { if(!_buf["item_type"].IsNumber) { throw new SerializationException(); }  ItemType = (Enums.Item.ItemType)_buf["item_type"].AsInt; }
        { var __json0 = _buf["use_change"]; if(!__json0.IsArray) { throw new SerializationException(); } UseChange = new System.Collections.Generic.List<Beans.Item_Draw>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Beans.Item_Draw __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Beans.Item_Draw.DeserializeItem_Draw(__e0);  }  UseChange.Add(__v0); }   }
        { if(!_buf["image_path"].IsString) { throw new SerializationException(); }  ImagePath = _buf["image_path"]; }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new item.Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string TextName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string TextDesc;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly Enums.Com.Quality Quality;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly Enums.Item.ItemType ItemType;
    /// <summary>
    /// 使用后转换为<br/>（此处第四个参数一定是概率万分数）
    /// </summary>
    public readonly System.Collections.Generic.List<Beans.Item_Draw> UseChange;
    /// <summary>
    /// 图片地址
    /// </summary>
    public readonly string ImagePath;
   
    public const int __ID__ = 2107285806;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UseChange) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "textName:" + TextName + ","
        + "textDesc:" + TextDesc + ","
        + "quality:" + Quality + ","
        + "itemType:" + ItemType + ","
        + "useChange:" + Luban.StringUtil.CollectionToString(UseChange) + ","
        + "imagePath:" + ImagePath + ","
        + "}";
    }
}

}

