
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Com
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum CondType
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 解锁武器（战斗中）
        /// </summary>
        WEAPONUNLOCK = 1,
        /// <summary>
        /// 武器等级（战斗前）
        /// </summary>
        WEAPONLEVEL = 2,
        /// <summary>
        /// 关卡等级
        /// </summary>
        DUNGEON_PASS = 3,
        /// <summary>
        /// 登录天数
        /// </summary>
        LOAD_DAY = 4,
        /// <summary>
        /// 总伤害（战斗中）
        /// </summary>
        TOTALBATTLEDAMAGE = 5,
        /// <summary>
        /// 0失败，1胜利
        /// </summary>
        BATTLE_STATE = 6,
        /// <summary>
        /// 1是主动放弃，2是被动空血
        /// </summary>
        BATTLE_LOSE_REASON = 7,
    }

} 

