
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Com
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum ParamType
    {
        /// <summary>
        /// 整型
        /// </summary>
        INT = 1,
        /// <summary>
        /// 64位整型
        /// </summary>
        INT64 = 2,
        /// <summary>
        /// 字符串
        /// </summary>
        STRING = 4,
        /// <summary>
        /// 时长
        /// </summary>
        TIMESPAN = 5,
        /// <summary>
        /// 资源
        /// </summary>
        RESOURCE = 6,
        /// <summary>
        /// 整型列表
        /// </summary>
        INT_LIST = 11,
        /// <summary>
        /// 资源列表
        /// </summary>
        RESOURCE_LIST = 16,
    }

} 

