
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Com
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum Quality
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 民用
        /// </summary>
        BLUE = 1,
        /// <summary>
        /// 军用
        /// </summary>
        PURPLE = 2,
        /// <summary>
        /// 机密
        /// </summary>
        ORANGE = 3,
    }

} 

