
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Com
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum ResourceType
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 道具
        /// </summary>
        ITEM = 1,
        /// <summary>
        /// 掉落包
        /// </summary>
        DROP = 2,
    }

} 

