
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Com
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum TriggerType
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 关卡X开始
        /// </summary>
        DUNGEON_START = 1,
        /// <summary>
        /// 关卡X结束
        /// </summary>
        DUNGEON_OVER = 2,
        /// <summary>
        /// 切换到指定UI
        /// </summary>
        UI_STATE = 3,
        /// <summary>
        /// 代码写死
        /// </summary>
        INCODE = 4,
        /// <summary>
        /// 1是成功，0是失败
        /// </summary>
        PLAYAD = 5,
        /// <summary>
        /// 三选一开始
        /// </summary>
        ON_TRICARD = 6,
        /// <summary>
        /// 三选一结束
        /// </summary>
        END_TRICARD = 7,
    }

} 

