
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbcom
{
/// <summary>
/// 全局参数
/// </summary>
public partial class GlobalParam
{
    private readonly System.Collections.Generic.Dictionary<string, com.GlobalParam> _dataMap;
    private readonly System.Collections.Generic.List<com.GlobalParam> _dataList;
    
    public GlobalParam(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, com.GlobalParam>();
        _dataList = new System.Collections.Generic.List<com.GlobalParam>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            com.GlobalParam _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.com.GlobalParam.DeserializeGlobalParam(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, com.GlobalParam> DataMap => _dataMap;
    public System.Collections.Generic.List<com.GlobalParam> DataList => _dataList;

    public com.GlobalParam GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public com.GlobalParam Get(string key) => _dataMap[key];
    public com.GlobalParam this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

