
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbcom
{
/// <summary>
/// 红点表
/// </summary>
public partial class RedDot
{
    private readonly System.Collections.Generic.Dictionary<int, com.RedDot> _dataMap;
    private readonly System.Collections.Generic.List<com.RedDot> _dataList;
    
    public RedDot(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, com.RedDot>();
        _dataList = new System.Collections.Generic.List<com.RedDot>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            com.RedDot _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.com.RedDot.DeserializeRedDot(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, com.RedDot> DataMap => _dataMap;
    public System.Collections.Generic.List<com.RedDot> DataList => _dataList;

    public com.RedDot GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public com.RedDot Get(int key) => _dataMap[key];
    public com.RedDot this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

