
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.card
{
public sealed partial class Card : Luban.BeanBase
{
    public Card(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["unlock_conds_bfbattle"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCondsBfbattle = new System.Collections.Generic.List<Beans.Com_UnlockConds>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Beans.Com_UnlockConds __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Beans.Com_UnlockConds.DeserializeCom_UnlockConds(__e0);  }  UnlockCondsBfbattle.Add(__v0); }   }
        { var __json0 = _buf["unlock_conds_inbattle"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCondsInbattle = new System.Collections.Generic.List<Beans.Com_UnlockConds>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Beans.Com_UnlockConds __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Beans.Com_UnlockConds.DeserializeCom_UnlockConds(__e0);  }  UnlockCondsInbattle.Add(__v0); }   }
        { if(!_buf["text_target_name"].IsString) { throw new SerializationException(); }  TextTargetName = _buf["text_target_name"]; }
        { if(!_buf["text_name"].IsString) { throw new SerializationException(); }  TextName = _buf["text_name"]; }
        { if(!_buf["text_desc"].IsString) { throw new SerializationException(); }  TextDesc = _buf["text_desc"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (Enums.Com.Quality)_buf["quality"].AsInt; }
        { if(!_buf["image_tricardicon_path"].IsString) { throw new SerializationException(); }  ImageTricardiconPath = _buf["image_tricardicon_path"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
        { var __json0 = _buf["card_effects"]; if(!__json0.IsArray) { throw new SerializationException(); } CardEffects = new System.Collections.Generic.List<Beans.card_Effects>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Beans.card_Effects __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Beans.card_Effects.Deserializecard_Effects(__e0);  }  CardEffects.Add(__v0); }   }
        { if(!_buf["draw_count"].IsNumber) { throw new SerializationException(); }  DrawCount = _buf["draw_count"]; }
    }

    public static Card DeserializeCard(JSONNode _buf)
    {
        return new card.Card(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 战斗前加载的条件<br/>（多个之间取并集&amp;&amp;）
    /// </summary>
    public readonly System.Collections.Generic.List<Beans.Com_UnlockConds> UnlockCondsBfbattle;
    /// <summary>
    /// 战斗中抽取的条件<br/>（多个之间取并集&amp;&amp;）
    /// </summary>
    public readonly System.Collections.Generic.List<Beans.Com_UnlockConds> UnlockCondsInbattle;
    /// <summary>
    /// 生效对象名称
    /// </summary>
    public readonly string TextTargetName;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string TextName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string TextDesc;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Enums.Com.Quality Quality;
    /// <summary>
    /// 使用图标
    /// </summary>
    public readonly string ImageTricardiconPath;
    /// <summary>
    /// 抽取权重
    /// </summary>
    public readonly int Weight;
    public readonly System.Collections.Generic.List<Beans.card_Effects> CardEffects;
    /// <summary>
    /// 单局可被抽取次数
    /// </summary>
    public readonly int DrawCount;
   
    public const int __ID__ = -291760306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockCondsBfbattle) { _e?.ResolveRef(tables); }
        foreach (var _e in UnlockCondsInbattle) { _e?.ResolveRef(tables); }
        foreach (var _e in CardEffects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "unlockCondsBfbattle:" + Luban.StringUtil.CollectionToString(UnlockCondsBfbattle) + ","
        + "unlockCondsInbattle:" + Luban.StringUtil.CollectionToString(UnlockCondsInbattle) + ","
        + "textTargetName:" + TextTargetName + ","
        + "textName:" + TextName + ","
        + "textDesc:" + TextDesc + ","
        + "quality:" + Quality + ","
        + "imageTricardiconPath:" + ImageTricardiconPath + ","
        + "weight:" + Weight + ","
        + "cardEffects:" + Luban.StringUtil.CollectionToString(CardEffects) + ","
        + "drawCount:" + DrawCount + ","
        + "}";
    }
}

}

