
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.card
{
public sealed partial class Card : Luban.BeanBase
{
    public Card(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["text_name"].IsString) { throw new SerializationException(); }  TextName = _buf["text_name"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (Enums.Com.Quality)_buf["quality"].AsInt; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
        { if(!_buf["draw_count"].IsNumber) { throw new SerializationException(); }  DrawCount = _buf["draw_count"]; }
    }

    public static Card DeserializeCard(JSONNode _buf)
    {
        return new card.Card(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string TextName;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Enums.Com.Quality Quality;
    /// <summary>
    /// 抽取权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 单局可被抽取次数
    /// </summary>
    public readonly int DrawCount;
   
    public const int __ID__ = -291760306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "textName:" + TextName + ","
        + "quality:" + Quality + ","
        + "weight:" + Weight + ","
        + "drawCount:" + DrawCount + ","
        + "}";
    }
}

}

