
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Bullet
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum Container
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 正常
        /// </summary>
        NORMAL = 1,
        /// <summary>
        /// 星球
        /// </summary>
        PLAYER = 2,
        /// <summary>
        /// 敌人
        /// </summary>
        ENEMY = 3,
        /// <summary>
        /// 玩家武器
        /// </summary>
        PLAYERWEAPON = 4,
    }

} 

