
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Bullet
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum TrackType
    {
        /// <summary>
        /// 不跟踪
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 曲线跟踪
        /// </summary>
        SLERP = 1,
        /// <summary>
        /// 镭射跟踪
        /// </summary>
        LASER = 2,
    }

} 

