
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.player
{
public sealed partial class PlayerAttrLevel : Luban.BeanBase
{
    public PlayerAttrLevel(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["earth_hp"].IsNumber) { throw new SerializationException(); }  EarthHp = _buf["earth_hp"]; }
    }

    public static PlayerAttrLevel DeserializePlayerAttrLevel(JSONNode _buf)
    {
        return new player.PlayerAttrLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 城防血量
    /// </summary>
    public readonly int EarthHp;
   
    public const int __ID__ = -2070093563;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "earthHp:" + EarthHp + ","
        + "}";
    }
}

}

