
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.player
{
public sealed partial class PlayerAttrLevel : Luban.BeanBase
{
    public PlayerAttrLevel(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["basic_hp"].IsObject) { throw new SerializationException(); }  BasicHp = global::cfg.Beans.Com_ValueResPair.DeserializeCom_ValueResPair(_buf["basic_hp"]);  }
        { if(!_buf["basic_atk"].IsObject) { throw new SerializationException(); }  BasicAtk = global::cfg.Beans.Com_ValueResPair.DeserializeCom_ValueResPair(_buf["basic_atk"]);  }
    }

    public static PlayerAttrLevel DeserializePlayerAttrLevel(JSONNode _buf)
    {
        return new player.PlayerAttrLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    public readonly Beans.Com_ValueResPair BasicHp;
    public readonly Beans.Com_ValueResPair BasicAtk;
   
    public const int __ID__ = -2070093563;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BasicHp?.ResolveRef(tables);
        BasicAtk?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "basicHp:" + BasicHp + ","
        + "basicAtk:" + BasicAtk + ","
        + "}";
    }
}

}

