
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.player
{
public sealed partial class PlayerData : Luban.BeanBase
{
    public PlayerData(JSONNode _buf) 
    {
        { if(!_buf["data_str"].IsString) { throw new SerializationException(); }  DataStr = _buf["data_str"]; }
        { if(!_buf["param_type"].IsNumber) { throw new SerializationException(); }  ParamType = (Enums.Com.ParamType)_buf["param_type"].AsInt; }
        { if(!_buf["param_value_init"].IsString) { throw new SerializationException(); }  ParamValueInit = _buf["param_value_init"]; }
    }

    public static PlayerData DeserializePlayerData(JSONNode _buf)
    {
        return new player.PlayerData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string DataStr;
    /// <summary>
    /// 参数数据类型
    /// </summary>
    public readonly Enums.Com.ParamType ParamType;
    /// <summary>
    /// 初始的参数值
    /// </summary>
    public readonly string ParamValueInit;
   
    public const int __ID__ = 2104369016;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "dataStr:" + DataStr + ","
        + "paramType:" + ParamType + ","
        + "paramValueInit:" + ParamValueInit + ","
        + "}";
    }
}

}

