
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbcard
{
/// <summary>
/// 3选1卡组表
/// </summary>
public partial class Card
{
    private readonly System.Collections.Generic.Dictionary<int, card.Card> _dataMap;
    private readonly System.Collections.Generic.List<card.Card> _dataList;
    
    public Card(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, card.Card>();
        _dataList = new System.Collections.Generic.List<card.Card>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            card.Card _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.card.Card.DeserializeCard(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, card.Card> DataMap => _dataMap;
    public System.Collections.Generic.List<card.Card> DataList => _dataList;

    public card.Card GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public card.Card Get(int key) => _dataMap[key];
    public card.Card this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

