
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.dungeon
{
public sealed partial class DungeonWave : Luban.BeanBase
{
    public DungeonWave(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["enemy_create"]; if(!__json0.IsArray) { throw new SerializationException(); } EnemyCreate = new System.Collections.Generic.List<Beans.Wave_EnemyCreate>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Beans.Wave_EnemyCreate __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Beans.Wave_EnemyCreate.DeserializeWave_EnemyCreate(__e0);  }  EnemyCreate.Add(__v0); }   }
    }

    public static DungeonWave DeserializeDungeonWave(JSONNode _buf)
    {
        return new dungeon.DungeonWave(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.List<Beans.Wave_EnemyCreate> EnemyCreate;
   
    public const int __ID__ = 782460799;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in EnemyCreate) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "enemyCreate:" + Luban.StringUtil.CollectionToString(EnemyCreate) + ","
        + "}";
    }
}

}

