
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.dungeon
{
public sealed partial class DungeonExp : Luban.BeanBase
{
    public DungeonExp(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["next_exp"].IsNumber) { throw new SerializationException(); }  NextExp = _buf["next_exp"]; }
    }

    public static DungeonExp DeserializeDungeonExp(JSONNode _buf)
    {
        return new dungeon.DungeonExp(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 升到下一级所需的经验
    /// </summary>
    public readonly int NextExp;
   
    public const int __ID__ = -1775891241;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "nextExp:" + NextExp + ","
        + "}";
    }
}

}

