
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.dungeon
{
public sealed partial class Dungeon : Luban.BeanBase
{
    public Dungeon(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["text_name"].IsString) { throw new SerializationException(); }  TextName = _buf["text_name"]; }
        { var __json0 = _buf["portals"]; if(!__json0.IsArray) { throw new SerializationException(); } Portals = new System.Collections.Generic.List<Beans.Dungeon_Portals>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Beans.Dungeon_Portals __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Beans.Dungeon_Portals.DeserializeDungeon_Portals(__e0);  }  Portals.Add(__v0); }   }
    }

    public static Dungeon DeserializeDungeon(JSONNode _buf)
    {
        return new dungeon.Dungeon(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡名称
    /// </summary>
    public readonly string TextName;
    public readonly System.Collections.Generic.List<Beans.Dungeon_Portals> Portals;
   
    public const int __ID__ = -841579674;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Portals) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "textName:" + TextName + ","
        + "portals:" + Luban.StringUtil.CollectionToString(Portals) + ","
        + "}";
    }
}

}

