
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Tbcom.GlobalParam GlobalParam {get; }
    public Tbweapon.Weapon Weapon {get; }
    public Tbdungeon.Dungeon Dungeon {get; }
    public Tbdungeon.Wave Wave {get; }
    public Tbenemy.Enemy Enemy {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GlobalParam = new Tbcom.GlobalParam(loader("com_global_param"));
        Weapon = new Tbweapon.Weapon(loader("weapon"));
        Dungeon = new Tbdungeon.Dungeon(loader("dungeon"));
        Wave = new Tbdungeon.Wave(loader("dungeon_wave"));
        Enemy = new Tbenemy.Enemy(loader("enemy"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GlobalParam.ResolveRef(this);
        Weapon.ResolveRef(this);
        Dungeon.ResolveRef(this);
        Wave.ResolveRef(this);
        Enemy.ResolveRef(this);
    }
}

}
