
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Tbcom.GlobalParam GlobalParam {get; }
    public Tbweapon.Weapon Weapon {get; }
    public Tbweapon.WeaponLevel WeaponLevel {get; }
    public Tbdungeon.Dungeon Dungeon {get; }
    public Tbdungeon.DungeonWave DungeonWave {get; }
    public Tbenemy.Enemy Enemy {get; }
    public Tbenemy.EnemyLevel EnemyLevel {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GlobalParam = new Tbcom.GlobalParam(loader("com_global_param"));
        Weapon = new Tbweapon.Weapon(loader("weapon"));
        WeaponLevel = new Tbweapon.WeaponLevel(loader("weapon_level"));
        Dungeon = new Tbdungeon.Dungeon(loader("dungeon"));
        DungeonWave = new Tbdungeon.DungeonWave(loader("dungeon_wave"));
        Enemy = new Tbenemy.Enemy(loader("enemy"));
        EnemyLevel = new Tbenemy.EnemyLevel(loader("enemy_level"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GlobalParam.ResolveRef(this);
        Weapon.ResolveRef(this);
        WeaponLevel.ResolveRef(this);
        Dungeon.ResolveRef(this);
        DungeonWave.ResolveRef(this);
        Enemy.ResolveRef(this);
        EnemyLevel.ResolveRef(this);
    }
}

}
