
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbshop
{
/// <summary>
/// 商店抽卡表
/// </summary>
public partial class drawLevel
{
    private readonly System.Collections.Generic.Dictionary<int, shop.drawLevel> _dataMap;
    private readonly System.Collections.Generic.List<shop.drawLevel> _dataList;
    
    public drawLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, shop.drawLevel>();
        _dataList = new System.Collections.Generic.List<shop.drawLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            shop.drawLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.shop.drawLevel.DeserializedrawLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, shop.drawLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<shop.drawLevel> DataList => _dataList;

    public shop.drawLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public shop.drawLevel Get(int key) => _dataMap[key];
    public shop.drawLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

