
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.enemy
{
public sealed partial class EnemyTypeIndex : Luban.BeanBase
{
    public EnemyTypeIndex(JSONNode _buf) 
    {
        { if(!_buf["enemy_type"].IsNumber) { throw new SerializationException(); }  EnemyType = (Enums.Enemy.Type)_buf["enemy_type"].AsInt; }
        { if(!_buf["exp"].IsNumber) { throw new SerializationException(); }  Exp = _buf["exp"]; }
    }

    public static EnemyTypeIndex DeserializeEnemyTypeIndex(JSONNode _buf)
    {
        return new enemy.EnemyTypeIndex(_buf);
    }

    /// <summary>
    /// 怪物类型
    /// </summary>
    public readonly Enums.Enemy.Type EnemyType;
    /// <summary>
    /// 击杀获得经验
    /// </summary>
    public readonly int Exp;
   
    public const int __ID__ = 1119844950;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enemyType:" + EnemyType + ","
        + "exp:" + Exp + ","
        + "}";
    }
}

}

