
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.enemy
{
public sealed partial class EnemyLevel : Luban.BeanBase
{
    public EnemyLevel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["damage_multi"].IsNumber) { throw new SerializationException(); }  DamageMulti = _buf["damage_multi"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["hp_multi"].IsNumber) { throw new SerializationException(); }  HpMulti = _buf["hp_multi"]; }
    }

    public static EnemyLevel DeserializeEnemyLevel(JSONNode _buf)
    {
        return new enemy.EnemyLevel(_buf);
    }

    /// <summary>
    /// 组id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 基础伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 基础伤害成长率
    /// </summary>
    public readonly int DamageMulti;
    /// <summary>
    /// 基础血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 基础血量成长率
    /// </summary>
    public readonly int HpMulti;
   
    public const int __ID__ = -1961363678;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "damage:" + Damage + ","
        + "damageMulti:" + DamageMulti + ","
        + "hp:" + Hp + ","
        + "hpMulti:" + HpMulti + ","
        + "}";
    }
}

}

