
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Drop
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum DropType
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 根据权重随机一个
        /// </summary>
        WEIGHT = 1,
        /// <summary>
        /// 根据概率瀑布计算
        /// </summary>
        PROP = 2,
    }

} 

