
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.com
{
public sealed partial class Color : Luban.BeanBase
{
    public Color(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["color_lightbg"].IsString) { throw new SerializationException(); }  ColorLightbg = _buf["color_lightbg"]; }
        { if(!_buf["color_darkbg"].IsString) { throw new SerializationException(); }  ColorDarkbg = _buf["color_darkbg"]; }
    }

    public static Color DeserializeColor(JSONNode _buf)
    {
        return new com.Color(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 亮底板的字体颜色
    /// </summary>
    public readonly string ColorLightbg;
    /// <summary>
    /// 暗底板的字体颜色
    /// </summary>
    public readonly string ColorDarkbg;
   
    public const int __ID__ = 964937878;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "colorLightbg:" + ColorLightbg + ","
        + "colorDarkbg:" + ColorDarkbg + ","
        + "}";
    }
}

}

