
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.com
{
public sealed partial class GlobalParam : Luban.BeanBase
{
    public GlobalParam(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["param_type"].IsNumber) { throw new SerializationException(); }  ParamType = (Enums.Com.ParamType)_buf["param_type"].AsInt; }
        { if(!_buf["int_value"].IsNumber) { throw new SerializationException(); }  IntValue = _buf["int_value"]; }
        { if(!_buf["str_value"].IsString) { throw new SerializationException(); }  StrValue = _buf["str_value"]; }
    }

    public static GlobalParam DeserializeGlobalParam(JSONNode _buf)
    {
        return new com.GlobalParam(_buf);
    }

    /// <summary>
    /// 参数名
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 参数说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 参数类型
    /// </summary>
    public readonly Enums.Com.ParamType ParamType;
    /// <summary>
    /// 整型值
    /// </summary>
    public readonly int IntValue;
    /// <summary>
    /// 字符串值
    /// </summary>
    public readonly string StrValue;
   
    public const int __ID__ = -820012643;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "desc:" + Desc + ","
        + "paramType:" + ParamType + ","
        + "intValue:" + IntValue + ","
        + "strValue:" + StrValue + ","
        + "}";
    }
}

}

