
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.weapon
{
public sealed partial class Bullet : Luban.BeanBase
{
    public Bullet(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["bullet_prefab"].IsString) { throw new SerializationException(); }  BulletPrefab = _buf["bullet_prefab"]; }
        { if(!_buf["parent_container"].IsNumber) { throw new SerializationException(); }  ParentContainer = (Enums.Bullet.Container)_buf["parent_container"].AsInt; }
        { if(!_buf["rotate_by_parent"].IsBoolean) { throw new SerializationException(); }  RotateByParent = _buf["rotate_by_parent"]; }
        { var _j = _buf["position_offset"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsObject) { throw new SerializationException(); }  PositionOffset = ExternalTypeUtil.NewVector2(global::cfg.Vector2.DeserializeVector2(_j));  } } else { PositionOffset = null; } }
        { if(!_buf["is_single_attack"].IsBoolean) { throw new SerializationException(); }  IsSingleAttack = _buf["is_single_attack"]; }
        { if(!_buf["single_attack_multi"].IsNumber) { throw new SerializationException(); }  SingleAttackMulti = _buf["single_attack_multi"]; }
        { if(!_buf["uncol_time"].IsNumber) { throw new SerializationException(); }  UncolTime = _buf["uncol_time"]; }
        { if(!_buf["track_type"].IsNumber) { throw new SerializationException(); }  TrackType = (Enums.Bullet.TrackType)_buf["track_type"].AsInt; }
        { if(!_buf["track_start_time"].IsNumber) { throw new SerializationException(); }  TrackStartTime = _buf["track_start_time"]; }
        { if(!_buf["track_angle_speed"].IsNumber) { throw new SerializationException(); }  TrackAngleSpeed = _buf["track_angle_speed"]; }
        { if(!_buf["group_damage_multi"].IsNumber) { throw new SerializationException(); }  GroupDamageMulti = _buf["group_damage_multi"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["life_time"].IsNumber) { throw new SerializationException(); }  LifeTime = _buf["life_time"]; }
        { if(!_buf["penetrate_sep"].IsNumber) { throw new SerializationException(); }  PenetrateSep = _buf["penetrate_sep"]; }
        { if(!_buf["penetrate_count"].IsNumber) { throw new SerializationException(); }  PenetrateCount = _buf["penetrate_count"]; }
        { if(!_buf["penetrate_damage_multi"].IsNumber) { throw new SerializationException(); }  PenetrateDamageMulti = _buf["penetrate_damage_multi"]; }
        { if(!_buf["row_space"].IsNumber) { throw new SerializationException(); }  RowSpace = _buf["row_space"]; }
        { if(!_buf["row_angle_sep"].IsNumber) { throw new SerializationException(); }  RowAngleSep = _buf["row_angle_sep"]; }
        { var _j = _buf["next_col_bullet"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  NextColBullet = _j; } } else { NextColBullet = null; } }
        NextColBullet_Ref = null;
        { if(!_buf["next_col_bullet_row"].IsNumber) { throw new SerializationException(); }  NextColBulletRow = _buf["next_col_bullet_row"]; }
        { var _j = _buf["next_lifetime_bullet"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  NextLifetimeBullet = _j; } } else { NextLifetimeBullet = null; } }
        NextLifetimeBullet_Ref = null;
        { if(!_buf["next_lifetime_bullet_row"].IsNumber) { throw new SerializationException(); }  NextLifetimeBulletRow = _buf["next_lifetime_bullet_row"]; }
    }

    public static Bullet DeserializeBullet(JSONNode _buf)
    {
        return new weapon.Bullet(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 子弹预制体地址<br/>（相对于Resources/Prefabs/Bullets）
    /// </summary>
    public readonly string BulletPrefab;
    /// <summary>
    /// 父物体容器
    /// </summary>
    public readonly Enums.Bullet.Container ParentContainer;
    /// <summary>
    /// 是否跟随父物体旋转
    /// </summary>
    public readonly bool RotateByParent;
    /// <summary>
    /// 父物体偏移
    /// </summary>
    public readonly UnityEngine.Vector2? PositionOffset;
    /// <summary>
    /// 是否有指向性碰撞<br/>（无视是否相交，返回附着/跟踪单位/第一个碰撞的单位）
    /// </summary>
    public readonly bool IsSingleAttack;
    /// <summary>
    /// 指向性碰撞伤害倍率
    /// </summary>
    public readonly int SingleAttackMulti;
    /// <summary>
    /// 子弹出生不攻击时间<br/>（派生子弹可以用这个来无法攻击父物体）
    /// </summary>
    public readonly float UncolTime;
    /// <summary>
    /// 跟踪方式
    /// </summary>
    public readonly Enums.Bullet.TrackType TrackType;
    /// <summary>
    /// 跟踪开始时间<br/>（前面X秒不跟踪）
    /// </summary>
    public readonly float TrackStartTime;
    /// <summary>
    /// 跟踪旋转角速度
    /// </summary>
    public readonly float TrackAngleSpeed;
    /// <summary>
    /// 群体碰撞伤害倍率<br/>（万分数）
    /// </summary>
    public readonly int GroupDamageMulti;
    /// <summary>
    /// 子弹飞行速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 最长生存时间（秒）
    /// </summary>
    public readonly float LifeTime;
    /// <summary>
    /// 基础单次子弹对同一个单位的伤害间隔（秒）
    /// </summary>
    public readonly float PenetrateSep;
    /// <summary>
    /// 基础子弹进行X次攻击后销毁（穿透）<br/>-1代表不会根据穿透与否销毁
    /// </summary>
    public readonly int PenetrateCount;
    /// <summary>
    /// 连续碰撞的伤害递减<br/>（万分数）
    /// </summary>
    public readonly int PenetrateDamageMulti;
    /// <summary>
    /// 当多个生成时的间隔像素
    /// </summary>
    public readonly float RowSpace;
    /// <summary>
    /// 同行多个同时生成时，错开的角度<br/>（目前以后续生成的方式实现的，会按圆角分割）
    /// </summary>
    public readonly float RowAngleSep;
    /// <summary>
    /// 后续生成<br/>（碰撞）
    /// </summary>
    public readonly int? NextColBullet;
    public weapon.Bullet NextColBullet_Ref;
    /// <summary>
    /// 后续生成数量<br/>（碰撞）
    /// </summary>
    public readonly int NextColBulletRow;
    /// <summary>
    /// 后续生成<br/>（时限）
    /// </summary>
    public readonly int? NextLifetimeBullet;
    public weapon.Bullet NextLifetimeBullet_Ref;
    /// <summary>
    /// 后续生成数量<br/>（时限）
    /// </summary>
    public readonly int NextLifetimeBulletRow;
   
    public const int __ID__ = 399957300;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        NextColBullet_Ref = NextColBullet!= null ? tables.Bullet.GetOrDefault(NextColBullet.Value) : null;
        NextLifetimeBullet_Ref = NextLifetimeBullet!= null ? tables.Bullet.GetOrDefault(NextLifetimeBullet.Value) : null;
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "bulletPrefab:" + BulletPrefab + ","
        + "parentContainer:" + ParentContainer + ","
        + "rotateByParent:" + RotateByParent + ","
        + "positionOffset:" + PositionOffset + ","
        + "isSingleAttack:" + IsSingleAttack + ","
        + "singleAttackMulti:" + SingleAttackMulti + ","
        + "uncolTime:" + UncolTime + ","
        + "trackType:" + TrackType + ","
        + "trackStartTime:" + TrackStartTime + ","
        + "trackAngleSpeed:" + TrackAngleSpeed + ","
        + "groupDamageMulti:" + GroupDamageMulti + ","
        + "speed:" + Speed + ","
        + "lifeTime:" + LifeTime + ","
        + "penetrateSep:" + PenetrateSep + ","
        + "penetrateCount:" + PenetrateCount + ","
        + "penetrateDamageMulti:" + PenetrateDamageMulti + ","
        + "rowSpace:" + RowSpace + ","
        + "rowAngleSep:" + RowAngleSep + ","
        + "nextColBullet:" + NextColBullet + ","
        + "nextColBulletRow:" + NextColBulletRow + ","
        + "nextLifetimeBullet:" + NextLifetimeBullet + ","
        + "nextLifetimeBulletRow:" + NextLifetimeBulletRow + ","
        + "}";
    }
}

}

