
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.weapon
{
public sealed partial class Bullet : Luban.BeanBase
{
    public Bullet(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["bullet_prefab"].IsString) { throw new SerializationException(); }  BulletPrefab = _buf["bullet_prefab"]; }
        { if(!_buf["can_col"].IsBoolean) { throw new SerializationException(); }  CanCol = _buf["can_col"]; }
        { if(!_buf["uncol_time"].IsNumber) { throw new SerializationException(); }  UncolTime = _buf["uncol_time"]; }
        { if(!_buf["track_type"].IsNumber) { throw new SerializationException(); }  TrackType = (Enums.Bullet.TrackType)_buf["track_type"].AsInt; }
        { if(!_buf["track_start_time"].IsNumber) { throw new SerializationException(); }  TrackStartTime = _buf["track_start_time"]; }
        { if(!_buf["damage_multi"].IsNumber) { throw new SerializationException(); }  DamageMulti = _buf["damage_multi"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["life_time"].IsNumber) { throw new SerializationException(); }  LifeTime = _buf["life_time"]; }
        { if(!_buf["penetrate_sep"].IsNumber) { throw new SerializationException(); }  PenetrateSep = _buf["penetrate_sep"]; }
        { if(!_buf["penetrate_count"].IsNumber) { throw new SerializationException(); }  PenetrateCount = _buf["penetrate_count"]; }
        { if(!_buf["row_space"].IsNumber) { throw new SerializationException(); }  RowSpace = _buf["row_space"]; }
        { if(!_buf["row_angle_sep"].IsNumber) { throw new SerializationException(); }  RowAngleSep = _buf["row_angle_sep"]; }
        { var _j = _buf["next_bullet"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  NextBullet = _j; } } else { NextBullet = null; } }
        NextBullet_Ref = null;
        { if(!_buf["next_bullet_row"].IsNumber) { throw new SerializationException(); }  NextBulletRow = _buf["next_bullet_row"]; }
    }

    public static Bullet DeserializeBullet(JSONNode _buf)
    {
        return new weapon.Bullet(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 子弹预制体地址<br/>（相对于Resources/Prefabs/Bullets）
    /// </summary>
    public readonly string BulletPrefab;
    /// <summary>
    /// 是否造成碰撞
    /// </summary>
    public readonly bool CanCol;
    /// <summary>
    /// 子弹出生无敌时间<br/>（派生子弹可以用这个来无法攻击父物体）
    /// </summary>
    public readonly float UncolTime;
    /// <summary>
    /// 跟踪方式
    /// </summary>
    public readonly Enums.Bullet.TrackType TrackType;
    /// <summary>
    /// 跟踪开始时间<br/>（前面X秒不跟踪）
    /// </summary>
    public readonly float TrackStartTime;
    /// <summary>
    /// 碰撞后的伤害倍率<br/>（万分数）
    /// </summary>
    public readonly int DamageMulti;
    /// <summary>
    /// 子弹飞行速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 最长生存时间（秒）
    /// </summary>
    public readonly float LifeTime;
    /// <summary>
    /// 基础单次子弹对同一个单位的伤害间隔（秒）
    /// </summary>
    public readonly float PenetrateSep;
    /// <summary>
    /// 基础子弹进行X次攻击后销毁（穿透）<br/>-1代表不会根据穿透与否销毁
    /// </summary>
    public readonly int PenetrateCount;
    /// <summary>
    /// 当多个生成时的间隔像素
    /// </summary>
    public readonly float RowSpace;
    /// <summary>
    /// 同行多个同时生成时，错开的角度<br/>（目前以后续生成的方式实现的，会按圆角分割）
    /// </summary>
    public readonly float RowAngleSep;
    /// <summary>
    /// 后续生成
    /// </summary>
    public readonly int? NextBullet;
    public weapon.Bullet NextBullet_Ref;
    /// <summary>
    /// 后续生成数量
    /// </summary>
    public readonly int NextBulletRow;
   
    public const int __ID__ = 399957300;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        NextBullet_Ref = NextBullet!= null ? tables.Bullet.GetOrDefault(NextBullet.Value) : null;
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "bulletPrefab:" + BulletPrefab + ","
        + "canCol:" + CanCol + ","
        + "uncolTime:" + UncolTime + ","
        + "trackType:" + TrackType + ","
        + "trackStartTime:" + TrackStartTime + ","
        + "damageMulti:" + DamageMulti + ","
        + "speed:" + Speed + ","
        + "lifeTime:" + LifeTime + ","
        + "penetrateSep:" + PenetrateSep + ","
        + "penetrateCount:" + PenetrateCount + ","
        + "rowSpace:" + RowSpace + ","
        + "rowAngleSep:" + RowAngleSep + ","
        + "nextBullet:" + NextBullet + ","
        + "nextBulletRow:" + NextBulletRow + ","
        + "}";
    }
}

}

