
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.weapon
{
public sealed partial class WeaponLevel : Luban.BeanBase
{
    public WeaponLevel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["damage_multi"].IsNumber) { throw new SerializationException(); }  DamageMulti = _buf["damage_multi"]; }
    }

    public static WeaponLevel DeserializeWeaponLevel(JSONNode _buf)
    {
        return new weapon.WeaponLevel(_buf);
    }

    /// <summary>
    /// 组id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 伤害加成率（万分数）
    /// </summary>
    public readonly int DamageMulti;
   
    public const int __ID__ = 327594454;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level:" + Level + ","
        + "damageMulti:" + DamageMulti + ","
        + "}";
    }
}

}

