
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.weapon
{
public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["text_name"].IsString) { throw new SerializationException(); }  TextName = _buf["text_name"]; }
        { if(!_buf["unlock_cond"].IsObject) { throw new SerializationException(); }  UnlockCond = global::cfg.Beans.Com_UnlockConds.DeserializeCom_UnlockConds(_buf["unlock_cond"]);  }
        { if(!_buf["init_quality"].IsNumber) { throw new SerializationException(); }  InitQuality = (Enums.Com.Quality)_buf["init_quality"].AsInt; }
        { if(!_buf["bullet_prefab"].IsString) { throw new SerializationException(); }  BulletPrefab = _buf["bullet_prefab"]; }
        { if(!_buf["piece"].IsNumber) { throw new SerializationException(); }  Piece = _buf["piece"]; }
        Piece_Ref = null;
        { if(!_buf["bullet_speed"].IsNumber) { throw new SerializationException(); }  BulletSpeed = _buf["bullet_speed"]; }
        { if(!_buf["max_lifetime"].IsNumber) { throw new SerializationException(); }  MaxLifetime = _buf["max_lifetime"]; }
        { if(!_buf["rate_of_fire"].IsNumber) { throw new SerializationException(); }  RateOfFire = _buf["rate_of_fire"]; }
        { if(!_buf["row_count"].IsNumber) { throw new SerializationException(); }  RowCount = _buf["row_count"]; }
        { if(!_buf["row_space"].IsNumber) { throw new SerializationException(); }  RowSpace = _buf["row_space"]; }
        { if(!_buf["column_count"].IsNumber) { throw new SerializationException(); }  ColumnCount = _buf["column_count"]; }
        { if(!_buf["column_space"].IsNumber) { throw new SerializationException(); }  ColumnSpace = _buf["column_space"]; }
        { if(!_buf["bullet_scale"].IsNumber) { throw new SerializationException(); }  BulletScale = _buf["bullet_scale"]; }
        { if(!_buf["level_id"].IsNumber) { throw new SerializationException(); }  LevelId = _buf["level_id"]; }
    }

    public static Weapon DeserializeWeapon(JSONNode _buf)
    {
        return new weapon.Weapon(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 武器名称
    /// </summary>
    public readonly string TextName;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly Beans.Com_UnlockConds UnlockCond;
    /// <summary>
    /// 初始稀有度
    /// </summary>
    public readonly Enums.Com.Quality InitQuality;
    /// <summary>
    /// 子弹预制体地址<br/>（相对于Resources/Prefabs/Bullets）
    /// </summary>
    public readonly string BulletPrefab;
    /// <summary>
    /// 绑定的碎片ID
    /// </summary>
    public readonly int Piece;
    public item.Item Piece_Ref;
    /// <summary>
    /// 子弹飞行速度
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// 最长生存时间（秒）
    /// </summary>
    public readonly float MaxLifetime;
    /// <summary>
    /// 发射频率<br/>（每秒发射X次）
    /// </summary>
    public readonly float RateOfFire;
    /// <summary>
    /// 基础1行几个
    /// </summary>
    public readonly int RowCount;
    /// <summary>
    /// 间隔像素
    /// </summary>
    public readonly float RowSpace;
    /// <summary>
    /// 基础连发几次
    /// </summary>
    public readonly int ColumnCount;
    /// <summary>
    /// 连发间隔（秒）
    /// </summary>
    public readonly float ColumnSpace;
    /// <summary>
    /// 子弹基础缩放
    /// </summary>
    public readonly int BulletScale;
    /// <summary>
    /// 等级组id（伤害等养成）
    /// </summary>
    public readonly int LevelId;
   
    public const int __ID__ = 986069582;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UnlockCond?.ResolveRef(tables);
        Piece_Ref = tables.Item.GetOrDefault(Piece);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "textName:" + TextName + ","
        + "unlockCond:" + UnlockCond + ","
        + "initQuality:" + InitQuality + ","
        + "bulletPrefab:" + BulletPrefab + ","
        + "piece:" + Piece + ","
        + "bulletSpeed:" + BulletSpeed + ","
        + "maxLifetime:" + MaxLifetime + ","
        + "rateOfFire:" + RateOfFire + ","
        + "rowCount:" + RowCount + ","
        + "rowSpace:" + RowSpace + ","
        + "columnCount:" + ColumnCount + ","
        + "columnSpace:" + ColumnSpace + ","
        + "bulletScale:" + BulletScale + ","
        + "levelId:" + LevelId + ","
        + "}";
    }
}

}

