
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbchest
{
/// <summary>
/// 循环宝箱
/// </summary>
public partial class ChestLoop
{
    private readonly System.Collections.Generic.List<chest.ChestLoop> _dataList;


    public ChestLoop(JSONNode _buf)
    {
        _dataList = new System.Collections.Generic.List<chest.ChestLoop>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            chest.ChestLoop _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.chest.ChestLoop.DeserializeChestLoop(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<chest.ChestLoop> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

