
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbweapon
{
/// <summary>
/// 武器表
/// </summary>
public partial class Weapon
{
    private readonly System.Collections.Generic.Dictionary<int, weapon.Weapon> _dataMap;
    private readonly System.Collections.Generic.List<weapon.Weapon> _dataList;
    
    public Weapon(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, weapon.Weapon>();
        _dataList = new System.Collections.Generic.List<weapon.Weapon>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            weapon.Weapon _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.weapon.Weapon.DeserializeWeapon(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, weapon.Weapon> DataMap => _dataMap;
    public System.Collections.Generic.List<weapon.Weapon> DataList => _dataList;

    public weapon.Weapon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public weapon.Weapon Get(int key) => _dataMap[key];
    public weapon.Weapon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

