
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbweapon
{
/// <summary>
/// 武器等级表
/// </summary>
public partial class WeaponLevel
{
    private readonly System.Collections.Generic.List<weapon.WeaponLevel> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), weapon.WeaponLevel> _dataMapUnion;

    public WeaponLevel(JSONNode _buf)
    {
        _dataList = new System.Collections.Generic.List<weapon.WeaponLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            weapon.WeaponLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.weapon.WeaponLevel.DeserializeWeaponLevel(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), weapon.WeaponLevel>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<weapon.WeaponLevel> DataList => _dataList;

    public weapon.WeaponLevel Get(int id, int level) => _dataMapUnion.TryGetValue((id, level), out weapon.WeaponLevel __v) ? __v : null;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

