
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Card
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum EffectsType
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 武器id,数量
        /// </summary>
        WEAPONCOLUMN = 1,
        /// <summary>
        /// 武器id,数量
        /// </summary>
        WEAPONROW = 2,
        /// <summary>
        /// 武器id（-1为全部）,数值
        /// </summary>
        WEAPONDAMAGE = 3,
        /// <summary>
        /// 武器id（-1为全部）,数值
        /// </summary>
        WEAPONCD = 4,
        /// <summary>
        /// 血量百分比
        /// </summary>
        HEAL = 5,
    }

} 

