
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Card
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum Type
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 武器解锁卡
        /// </summary>
        WEAPONUNLOCK = 1,
        /// <summary>
        /// 升级卡
        /// </summary>
        UPGRADE = 2,
    }

} 

