
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbplayer
{
public partial class PlayerAttrLevel
{
    private readonly System.Collections.Generic.Dictionary<int, player.PlayerAttrLevel> _dataMap;
    private readonly System.Collections.Generic.List<player.PlayerAttrLevel> _dataList;
    
    public PlayerAttrLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, player.PlayerAttrLevel>();
        _dataList = new System.Collections.Generic.List<player.PlayerAttrLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            player.PlayerAttrLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.player.PlayerAttrLevel.DeserializePlayerAttrLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, player.PlayerAttrLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<player.PlayerAttrLevel> DataList => _dataList;

    public player.PlayerAttrLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public player.PlayerAttrLevel Get(int key) => _dataMap[key];
    public player.PlayerAttrLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

