
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbplayer
{
/// <summary>
/// 玩家数据
/// </summary>
public partial class PlayerData
{
    private readonly System.Collections.Generic.Dictionary<string, player.PlayerData> _dataMap;
    private readonly System.Collections.Generic.List<player.PlayerData> _dataList;
    
    public PlayerData(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, player.PlayerData>();
        _dataList = new System.Collections.Generic.List<player.PlayerData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            player.PlayerData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.player.PlayerData.DeserializePlayerData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.DataStr, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, player.PlayerData> DataMap => _dataMap;
    public System.Collections.Generic.List<player.PlayerData> DataList => _dataList;

    public player.PlayerData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public player.PlayerData Get(string key) => _dataMap[key];
    public player.PlayerData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

