
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Enums.Enemy
{ 
    /// <summary>
    /// ,
    /// </summary>
    public enum Type
    {
        /// <summary>
        /// 空
        /// </summary>
        NULL = 0,
        /// <summary>
        /// 小兵
        /// </summary>
        TRASH = 1,
        /// <summary>
        /// 精英
        /// </summary>
        ELITE = 2,
        /// <summary>
        /// 首领
        /// </summary>
        BOSS = 3,
        /// <summary>
        /// 武器宝箱怪
        /// </summary>
        REWARDWEAPON = 4,
    }

} 

