
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbavg
{
/// <summary>
/// AVG事件
/// </summary>
public partial class AvgEvent
{
    private readonly System.Collections.Generic.Dictionary<int, avg.AvgEvent> _dataMap;
    private readonly System.Collections.Generic.List<avg.AvgEvent> _dataList;
    
    public AvgEvent(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, avg.AvgEvent>();
        _dataList = new System.Collections.Generic.List<avg.AvgEvent>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            avg.AvgEvent _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.avg.AvgEvent.DeserializeAvgEvent(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, avg.AvgEvent> DataMap => _dataMap;
    public System.Collections.Generic.List<avg.AvgEvent> DataList => _dataList;

    public avg.AvgEvent GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public avg.AvgEvent Get(int key) => _dataMap[key];
    public avg.AvgEvent this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

