
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Tbavg
{
/// <summary>
/// AVG事件组
/// </summary>
public partial class AvgStory
{
    private readonly System.Collections.Generic.Dictionary<int, avg.AvgStory> _dataMap;
    private readonly System.Collections.Generic.List<avg.AvgStory> _dataList;
    
    public AvgStory(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, avg.AvgStory>();
        _dataList = new System.Collections.Generic.List<avg.AvgStory>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            avg.AvgStory _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.avg.AvgStory.DeserializeAvgStory(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, avg.AvgStory> DataMap => _dataMap;
    public System.Collections.Generic.List<avg.AvgStory> DataList => _dataList;

    public avg.AvgStory GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public avg.AvgStory Get(int key) => _dataMap[key];
    public avg.AvgStory this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

